version: "3.9"
services:
   test_block:
      image: ubuntu:22.04
      container_name: ubuntu_main
      volumes:
        - '/home/a1/f_mou:/f_mou_dir'
      ports:
        - '443:443'
      restart: unless-stopped

    s_test_block:
      image: nginx:stable
      container_name: nginx_test
      volumes:
        - '/home/a1/f_mou:/f_mou_dir'
      ports:
        - '8080:80'
      restart: unless-stopped
networks:
   default:
      driver: bridge
      name: ubunt_web_net

